# Generated by Django 5.2.7 on 2025-11-02 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralMenuContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labelText', models.CharField(help_text='Display text for the menu item (e.g., Home, Cart, Support)', max_length=200, unique=True)),
                ('labelIcon', models.CharField(help_text='Font Awesome icon class (e.g., fa-solid fa-home)', max_length=50)),
                ('routeToLink', models.URLField(help_text='Destination link for this menu item', unique=True)),
                ('menuPage', models.CharField(choices=[('HOME', 'Home Page'), ('CART', 'Cart Page'), ('PROFILE', 'Profile Page'), ('ORDERS', 'Orders Page'), ('SETTINGS', 'Settings Page'), ('SUPPORT', 'Support Page'), ('AI_ASSIST', 'AI Assistant Page'), ('OTHER', 'Other / General')], default='OTHER', help_text='Specifies the logical page this menu item links to', max_length=50)),
                ('menuGroup', models.CharField(choices=[('HEADER', 'Header Menu'), ('SIDEBAR', 'Sidebar Menu'), ('FOOTER', 'Footer Menu')], default='HEADER', help_text='Defines which part of the site this menu appears in', max_length=50)),
                ('position', models.PositiveIntegerField(default=0, help_text='Order of appearance within the menu group')),
                ('is_active', models.BooleanField(default=True, help_text='If unchecked, this menu item will be hidden from users')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
