# Generated by Django 5.2.7 on 2025-11-02 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_generalmenucontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalmenucontent',
            name='menuGroup',
            field=models.CharField(choices=[('GENERAL', 'General menu'), ('HEADER', 'Header Menu'), ('SIDEBAR', 'Sidebar Menu'), ('FOOTER', 'Footer Menu')], default='HEADER', help_text='Defines which part of the site this menu appears in', max_length=50),
        ),
    ]
