# Generated by Django 5.2.7 on 2025-11-02 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_generalmenucontent_menugroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalmenucontent',
            name='routeToLink',
            field=models.CharField(help_text='Destination link for this menu item', unique=True),
        ),
    ]
