# Generated by Django 5.2.7 on 2025-11-02 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_generalmenucontent_routetolink'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryLabel', models.CharField(help_text='Categories of items', max_length=100, unique=True)),
            ],
        ),
    ]
